import { ColorValue } from 'react-native';

enum ColorsType {
  black = 'black',
  white = 'white',
  blue = 'blue',
  darkBlue = 'darkBlue',
  disabled = 'disabled',
  chambray = 'chambray',
  prussianBlue = 'prussianBlue',
  silverChalice = 'silverChalice',
  doveGray = 'doveGray',
  chatelle = 'chatelle',
  alabaster = 'alabaster',
  error = 'error',
  black_60 = 'black_60',
  black_38 = 'black_38',
  pressEffect = 'pressEffect',
  concrete = 'concrete',
  success = 'success',
  todo = 'todo',
  inprogress = 'inprogress',
  completed = 'completed',
}

export const Colors: Record<ColorsType, ColorValue> = {
  [ColorsType.black]: '#000000',
  [ColorsType.white]: '#ffffff',
  [ColorsType.blue]: '#232cc6',
  [ColorsType.darkBlue]: '#2028b6',
  [ColorsType.disabled]: '#898dce',
  [ColorsType.chambray]: '#405a9a',
  [ColorsType.prussianBlue]: '#001f5a',
  [ColorsType.silverChalice]: '#9e9e9e',
  [ColorsType.doveGray]: '#666666',
  [ColorsType.chatelle]: '#c2b9c3',
  [ColorsType.alabaster]: '#fbfbfb',
  [ColorsType.error]: '#de2c2c',
  [ColorsType.success]: '#28a745',
  [ColorsType.concrete]: '#f2f2f2',
  [ColorsType.black_60]: 'rgba(0, 0, 0, 0.6)',
  [ColorsType.black_38]: 'rgba(0, 0, 0, 0.38)',
  [ColorsType.pressEffect]: 'rgba(95,99,104,0.15)',
  [ColorsType.todo]: '#ff8c00',
  [ColorsType.inprogress]: '#1890ff',
  [ColorsType.completed]: '#52c41a',
};
