---
name: CI
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
jobs:
  build:
    name: Lint and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [12.x]
        os:
          - macos-latest
          - ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm ci
      - name: Run eslint
        run: npm run lint:eslint
      - name: Run types check
        run: npm run lint:types
      - name: Run tests
        run: npm run test
